# contract v1.8 part 3: drawing path, edge seal, crossfade rule, blink, Life, stress bypass
import sys
src,dst=sys.argv[1],sys.argv[2];s=open(src).read()
def R(old,new):
    global s
    n=s.count(old)
    if n!=1: raise SystemExit(f'anchor {n}x: {old[:80]!r}')
    s=s.replace(old,new)
def line(prefix,new):
    global s
    L=s.split('\n');idx=[i for i,l in enumerate(L) if l.startswith(prefix)]
    if len(idx)!=1: raise SystemExit(f'line {prefix!r} {len(idx)}x')
    L[idx[0]]=new;s='\n'.join(L)
line("**Crossfade rule (v1.3, applies everywhere).**",
 "**Crossfade rule (v1.8, applies everywhere).** The incoming image starts at 25% opacity on the switch frame itself (so no frame is lost) and reaches 100% at 3/4 of the fade. The outgoing image stays at full opacity for the first half, then fades to 0 over the second half. So there is no opaque underlay for the whole fade (v1.3 had one, which doubled the outline in the profiles at smile→rest), and the two never sit at low opacity together. With the 35 ms mouth fade this is one or two 60 Hz steps. A hard cut (`mouthfade=0`) skips both. Shape choice: the nearest grid shape to (`MouthOpen`, `MouthForm`). An exact tie between `rest` and another shape (for example `MouthForm` = 0.5) resolves to the other shape, the target. At the rest point itself `rest` is at distance 0 and always wins.")
line("- **Blinks (v1.8, Base Eyes):**",
 "- **Blinks (v1.8, Base Eyes):** about 330 ms per blink: snap shut in 42 ms, hold 165 ms, reopen in 125 ms with an ease-in, so the lid reads shut (open < 0.5) for about 250 ms. Random intervals of 2.5–5 s after the previous blink ends, both eyes together, upper lid frames only, no double blinks. A head turn that reverses (a `BodyLean` direction change of at least 0.05) also triggers a blink, but only if the last one ended at least 2.5 s ago.")
line("- **Body idle (v1.8, only with jointed body parts;",
 "- **Body idle, talk style (v1.8, only with jointed body parts; rig units ×25° limbs, ×8° lean):** breathing (4.6 s) on `BodyLean` ±0.22 (±1.76°), minus 0.06 (0.5°) of the weight shift. Shoulders: ±0.03 with the breath plus an independent slow drift ±0.07 (7.1 s / 6.4 s), so each arm moves up to about 2.5°. Elbows: ±0.06 (1.5°) lagging the shoulder drift by 0.35 s. Hips: the weight shift (every 7–14 s, eased over 1.6 s) at 0.1 (2.5°) plus a ±0.02 drift, both hips together, knees countering (`Knee = −Hip`) so the shins stay parallel to rest; slight toe lift on the unloaded side. The root comes from foot plant.\n"
 "- **Life (v1.8, idle style, default on):** a layered procedural secondary-motion system. UI `Life` 0–1 (URL `life=`, default 1) scales every amplitude; 0 is still. It is never applied at rest, so rest stays exact. The layers, in rig units: **Base:** Body's `idle_arm_sway` clip (`body_tools/idle/idle_clips.json`, 8 s loop, shoulders ±1.0, elbows up to 0.6 lagging 0.35 s, lean ±0.04, legs 0) × Life. **Breathing** (4.0 s): shoulders +0.04 out on the inhale, lean ±0.04, and the head rises up to 1.2 px (`HeadNod` −0.3, front/back) or pitches ±0.6° (profiles). The root does not breathe, because the feet stay planted. **Weight shift** (a new 6–10 s period each cycle): both hips ±0.08 (±2°), knees `−Hip` in front/back, so the shins stay vertical and the feet flat. In the profiles the loaded leg's knee gives up to 0.04 (1°) of flexion only (never hyperextension), with the hip and ankle compensating so the foot stays flat. Foot plant `xy` turns this into the pelvis sway (`RootX`). The torso counter-tilts (`BodyLean` −0.2 × sway, half in the profiles) through a damped follower (1.6 Hz, ζ 0.6). **Follow-through:** the head is a damped follower (2.2 Hz, ζ 0.55, about 2–3 frames of lag and about 12% overshoot on a step) of 45% of the torso angle plus its own slow drift (±2°, 5.7 s). The lag becomes `HeadTilt` (front/back) or `HeadNod` (profiles). The upper arm, forearm and hand are each damped followers (2.2 Hz, ζ 0.55) of their parent's world angle, so elbows and wrists trail the shoulders. **Hands:** finger curl drift 0.05–0.15 with per-finger phases (capped at 0.12 in tpose). This stays on frame f0 with 3 frames (switch at 0.25) and below the tpose f0→f1 switch at 0.125, so the fingers never pop. Wrist drift ±0.08 on top of the follower. **Eyes:** Base Eyes' blinks, a gaze drift of 0.04 eye width that leads the sway by 0.1 s (3 frames), and micro-saccades of ±0.03 eye width every 0.8–2 s. The iris moves in whole px within `irisLimitsPx` (1–3 px). **Mouth:** rest, with a soft smile (1.6–2.6 s) or a short `M` press (0.5–0.9 s) every 6–12 s, eased over 0.12 s, so there is one switch in and one out and no talk flicker. **Hair:** reacts through the springs, including the inertia input. Preview renders use preset `A` (labelled); the default stays `default`.")
line("- **Drawing (v1.8).**",
 "- **Drawing (v1.8).** Rest is drawn as before, with axis-aligned parts pixel-snapped and exact. Posed frames always take one resampling path: smoothed (linear) drawing at the exact transform for every part and the skin mesh, with no special case for 0° or axis-aligned transforms. `2x supersampled` (`ss2`) is now the default (URL `quality=`). A 0° part and a slightly rotated part are both drawn at 2× and downsampled, so a joint crossing 0° no longer switches a frame between exact and resampled. Before this, `linear` measured 8 steps over 1.5% and 3 sharp pulses in 5 s of apose idle. With `ss2` it measured 0 steps, 0 reversals and 0 spikes, with mean sharpness 0.96 of rest. Rest is always drawn 1:1.\n"
 "- **Edge seal (v1.8, default on, UI `Edge seal`, URL `seal=0|1`).** Abutting antialiased cut edges composited with source-over leave net partial alpha (a + b − ab < 1) where parts meet, so the background shows through. In posed frames the renderer also builds a coverage buffer: every item drawn again with `lighter`, i.e. premultiplied alphas summed and clamped at 1. The composite is then drawn over itself 8× with `destination-over`, which keeps its colour and drives alpha to 1, and masked `destination-in` by the coverage. Where only one layer is partial (the outer silhouette), coverage equals the composite's alpha and nothing changes. Where abutting partial layers sum past it, the seam becomes opaque in the composite's own colour. It uses drawImage and composite operations only; the dev guard, which forbids pixel writes, is unchanged. QA metric: pixels at least 4 px inside the silhouette with alpha < 255 (and < 240). Measured on a posed tpose/left test frame: < 240 went from 560 to 257 px (tpose) and 410 to 77 px (left). The rest of the count is the authored art's own near-opaque alpha (tpose rest already has 1,440 px < 255).\n"
 "- **Stress bypass (v1.8, render-only, default off).** `stressEnable(clip)` turns off the ±1 param clamp and widens the root clamp to ±400 px only when the clip carries `stressTest: true` (Body's `body_tools/actions/stress/*_stress.json`, merged with `rig/tools/merge_clips.py --stress`). Normal clips, the UI, rest and the guard are never affected.")
R("New reference-only section 12 (three-quarter measure targets).",
  "Posed frames use one resampling path (`ss2` default) and an edge seal. Mouth crossfade: incoming from the switch frame, outgoing fades over the last half. Blinks: ease-in reopen, 2.5 s minimum gap including turn blinks. New idle `Life` layer (section 7). Render-only stress bypass for `stressTest` clips. New reference-only section 12 (three-quarter measure targets).")
open(dst,'w').write(s);print('ok')
