/* Direct manipulation of the existing authored rig parameters. */
(() => {
'use strict';
const stage=document.getElementById('stage'),canvas=document.getElementById('c');
const style=document.createElement('style');style.textContent=`
#pose-toolbar{position:relative;margin:8px;flex-shrink:0;z-index:12;display:flex;flex-wrap:wrap;gap:4px;align-items:center;background:#171b23ed;padding:5px;border-radius:6px;color:#eee;font:12px system-ui;line-height:1.3}
#pose-toolbar button{min-height:30px;margin:0}#pose-toolbar input{width:100px}#pose-toolbar button[aria-pressed=true]{background:#24567e;border-color:#8cd4ff}#pose-readout{flex-basis:100%;color:#b9d8ed;min-height:16px}
#pose-surface{position:relative;flex:none;line-height:0;transform-origin:center;touch-action:none}#pose-surface canvas{display:block;max-width:none;max-height:none}#pose-nodes{position:absolute;inset:0;width:100%;height:100%;overflow:visible;pointer-events:none}#pose-nodes circle{pointer-events:all;cursor:grab;touch-action:none;stroke:#071a27;stroke-width:2;vector-effect:non-scaling-stroke;fill:#66d8ff}#pose-nodes circle:focus,#pose-nodes circle[data-selected=true]{fill:#ffd26a;outline:none;stroke:#fff}#pose-nodes line{stroke:#58bce4;stroke-width:1.5;vector-effect:non-scaling-stroke;opacity:.65;pointer-events:none}
body.pose-hide-controls #ui,body.pose-hide-layers #layers{display:none!important}#ui [hidden]{display:none!important}#ui h3.pose-fold{cursor:pointer}#ui h3.pose-fold:after{content:' ▾';color:#8bd7ff}#ui h3.pose-fold[aria-expanded=false]:after{content:' ▸'}#stage{touch-action:none;flex-direction:column;align-items:stretch;justify-content:flex-start}#pose-viewport{flex:1;min-height:0;position:relative;display:flex;align-items:center;justify-content:center;overflow:hidden}#pose-toolbar label{margin:0;align-items:center;gap:4px}#pose-toolbar input[type=range]{width:100px}
`;document.head.append(style);
const surface=document.createElement('div');surface.id='pose-surface';stage.insertBefore(surface,canvas);surface.append(canvas);const viewport=document.createElement('div');viewport.id='pose-viewport';stage.insertBefore(viewport,surface);viewport.append(surface);
const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.id='pose-nodes';svg.setAttribute('aria-label','Draggable pose joints');surface.append(svg);
let pref={};try{pref=JSON.parse(localStorage.getItem('shadowveil.pose.workspace.v1')||'{}')}catch{}
let zoom=1,panX=0,panY=0,nodesOn=pref.nodes!==false,panMode=false,twistMode=false,handFocusSide='',drag=null,selected='',nodes=[];
const toolbar=document.createElement('div');toolbar.id='pose-toolbar';toolbar.innerHTML='<button type="button" data-action="playback">Play motion</button><button type="button" data-action="controls">Controls</button><button type="button" data-action="layers">Layers</button><button type="button" data-action="nodes">Nodes</button><button type="button" data-action="twist">Twist handles</button><button type="button" data-action="handL">Left hand</button><button type="button" data-action="handR">Right hand</button><button type="button" data-action="pan">Pan</button><button type="button" data-action="out" aria-label="Zoom out">−</button><label>Zoom <input id="pose-zoom" aria-label="Pose zoom" type="range" min="0.5" max="4" step="0.1" value="1"></label><output id="pose-percent">100%</output><button type="button" data-action="in" aria-label="Zoom in">+</button><button type="button" data-action="fit">Fit</button><div id="pose-readout" role="status">Drag a joint handle to pose. Use Pan to move the view.</div>';stage.insertBefore(toolbar,viewport);
const readout=toolbar.querySelector('#pose-readout');
function signal(){try{window.parent.dispatchEvent(new Event('shadowveil-workspace-change'))}catch{}}
function save(){signal();try{localStorage.setItem('shadowveil.pose.workspace.v1',JSON.stringify(pref))}catch{}}
function togglePanel(which){const key=which==='controls'?'hideControls':'hideLayers';pref[key]=!pref[key];document.body.classList.toggle('pose-hide-'+which,pref[key]);toolbar.querySelector('[data-action='+which+']').setAttribute('aria-pressed',String(!pref[key]));save();fit();}
for(const which of ['controls','layers']){document.body.classList.toggle('pose-hide-'+which,!!pref[which==='controls'?'hideControls':'hideLayers']);toolbar.querySelector('[data-action='+which+']').setAttribute('aria-pressed',String(!pref[which==='controls'?'hideControls':'hideLayers']));}
function setZoom(value){zoom=Math.max(.5,Math.min(4,value));toolbar.querySelector('#pose-zoom').value=zoom;toolbar.querySelector('#pose-percent').textContent=Math.round(zoom*100)+'%';transform();update();}
function transform(){canvas.style.imageRendering='auto';surface.style.transform=`translate(${panX}px,${panY}px) scale(${zoom})`;}
function fit(){const w=Math.max(80,viewport.clientWidth-24),h=Math.max(100,viewport.clientHeight-24);const ratio=Math.min(w/canvas.width,h/canvas.height);canvas.style.width=canvas.width*ratio+'px';canvas.style.height=canvas.height*ratio+'px';transform();}
function point(M,x,y){return [M[0]*x+M[2]*y+M[4],M[1]*x+M[3]*y+M[5]];}
function coeff(b,k){const old=v[k];v[k]=1;const plus=bodyAngle(b);v[k]=-1;const minus=bodyAngle(b);v[k]=old;return [plus,minus];}
function fromAngle(a,plus,minus){const candidates=[0,1,-1];if(plus)candidates.push(Math.max(0,Math.min(1,a/plus)));if(minus)candidates.push(Math.max(-1,Math.min(0,-a/minus)));return candidates.sort((x,y)=>Math.abs((x>=0?x*plus:-x*minus)-a)-Math.abs((y>=0?y*plus:-y*minus)-a))[0];}
function collect(){if(!R)return [];const bones=useSkin()?R.skin.bones:R.body?.parts||[],BM=R._BM||{},result=[];
 for(const b of bones){const k=bodyParamOf(b);if(!k||!P[k]||inputs[k]?.disabled)continue;const M=BM[b.id]||I;let child=bones.find(q=>(q.parent!==undefined?q.parent:BODY_PARENT_OF[q.id])===b.id);let end=child?[child.pivotX,child.pivotY]:b.wristPivot?pt(b.wristPivot):[b.pivotX+45,b.pivotY+55];if(k==='BodyLean')end=[b.pivotX,b.pivotY-200];if(Math.hypot(end[0]-b.pivotX,end[1]-b.pivotY)<10)end=[b.pivotX,b.pivotY-120];result.push({key:k,label:k,pivot:point(M,b.pivotX,b.pivotY),end:point(M,...end),kind:'angle',angle:bodyAngle(b),coeff:coeff(b,k)});}
 if(R.neck){const M=BM[R.skin?.headBone]||BM.head||BM.torso||I;result.push({key:'HeadTilt',label:'Head tilt / nod',kind:'head',pivot:point(M,R.neck.x,R.neck.y),end:point(M,R.neck.x,R.neck.y-110)});}
 const pelvis=bones.find(b=>b.id==='pelvis');if(pelvis)result.push({key:'RootX',label:'Root position',kind:'root',pivot:point(BM.pelvis||I,pelvis.pivotX,pelvis.pivotY),end:point(BM.pelvis||I,pelvis.pivotX,pelvis.pivotY)});
 if(R.hands)for(const side of ['L','R']){const active=activeHandRig(side),j=active.rig;if(!j)continue;const nativePalm=R.hands.parts.find(p=>p.id===side+'_palm'&&p.file&&!p.hidden);if(!nativePalm)continue;const root=mul(palmExt(nativePalm,BM,false),active.fit);const HM=handChain(j.parts,handAngle(j),()=>root,false,active.frames);for(const p of j.parts){if(!p.file||p.hidden||!p.id.startsWith(side+'_'))continue;const palm=p.id.match(/^([LR])_palm$/),finger=p.id.match(/^([LR])_(Thumb|Index|Middle|Ring|Pinky)([123])$/);if(!palm&&!finger)continue;const k=palm?'Wrist'+side:'Hand'+side+finger[2]+finger[3];if(!P[k]||inputs[k]?.disabled)continue;const M=HM[p.id]||I;const child=j.parts.find(q=>q.parent===p.id);const f=frameOf(p,false,active.frames);const end=f?.childPivot||p.tip|| (child?[child.pivotX,child.pivotY]:[p.pivotX,p.pivotY+18]);const mx=palm?+(p.maxWristDeg??j.wristMaxDeg??25):+(p.maxCurlDeg||30);result.push({key:k,label:palm?k:side+' '+finger[2]+' joint '+finger[3],kind:palm?'angle':'curl',pivot:point(M,...(f?.pivot||[p.pivotX,p.pivotY])),end:point(M,...end),angle:palm?v[k]*mx:fingerCurl(p)*mx,coeff:[mx,palm?-mx:0]});}}

 if(twistMode){const map={ShoulderL:'ShoulderTwistL',ShoulderR:'ShoulderTwistR',ElbowL:'ForearmTwistL',ElbowR:'ForearmTwistR',HipL:'HipTwistL',HipR:'HipTwistR',KneeL:'KneeTwistL',KneeR:'KneeTwistR',AnkleL:'AnkleTwistL',AnkleR:'AnkleTwistR',HeadTilt:'NeckTwist',WristL:'WristTwistL',WristR:'WristTwistR'};const scale=Math.max(.05,canvas.getBoundingClientRect().width/(LP.zoom?.[2]||canvas.width));const out=[];for(const n of result){const key=map[n.key];if(!key||inputs[key]?.disabled)continue;const dx=n.end[0]-n.pivot[0],dy=n.end[1]-n.pivot[1],len=Math.hypot(dx,dy)||1,off=23/scale;const center=[(n.pivot[0]+n.end[0])/2,(n.pivot[1]+n.end[1])/2];out.push({...n,key,label:key+(/Wrist/.test(key)?' (authored hand angle)':' (localized skin twist)'),kind:'twist',end:[center[0]-dy/len*off,center[1]+dx/len*off]});}return out;}
 return result;
}
function update(){const playback=window.SVPlayback?.state;const play=toolbar.querySelector('[data-action=playback]');if(playback){play.textContent=playback.playing?'Pause motion':'Play motion';play.setAttribute('aria-pressed',String(playback.playing))}fit();if(!R){svg.replaceChildren();return;}const z=LP.zoom||Z.full;svg.setAttribute('viewBox',z.join(' '));nodes=collect();if(handFocusSide&&document.getElementById('zoom').value==='handFocus')nodes=nodes.filter(n=>n.key.startsWith('Hand'+handFocusSide)||n.key==='Wrist'+handFocusSide||n.key==='WristTwist'+handFocusSide);svg.style.display=nodesOn?'block':'none';const scale=canvas.getBoundingClientRect().width/(LP.zoom?.[2]||canvas.width);const radius=9/Math.max(scale,.02);const existing=new Map([...svg.querySelectorAll('circle')].map(e=>[e.dataset.key,e]));const fragment=document.createDocumentFragment();
 for(const n of nodes){const line=document.createElementNS(ns,'line');line.setAttribute('x1',n.pivot[0]);line.setAttribute('y1',n.pivot[1]);line.setAttribute('x2',n.end[0]);line.setAttribute('y2',n.end[1]);fragment.append(line);let circle=existing.get(n.key);const isNew=!circle;if(!circle){circle=document.createElementNS(ns,'circle');circle.dataset.key=n.key;circle.setAttribute('tabindex','0');circle.setAttribute('role','slider');circle.setAttribute('aria-label',n.label);const title=document.createElementNS(ns,'title');title.textContent=n.label;circle.append(title);}circle.setAttribute('cx',n.end[0]);circle.setAttribute('cy',n.end[1]);circle.setAttribute('r',n.kind==='curl'?radius*.55:radius);circle.setAttribute('aria-valuemin',P[n.key][0]);circle.setAttribute('aria-valuemax',P[n.key][1]);circle.setAttribute('aria-valuenow',v[n.key]);circle.style.fill=n.kind==='twist'?'#d5a1ff':'';circle.dataset.selected=String(selected===n.key);if(isNew)svg.append(circle);}
 // Keep captured handles attached while dragging.
 const wanted=new Set(nodes.map(n=>n.key));for(const old of svg.querySelectorAll('line'))old.remove();for(const old of svg.querySelectorAll('circle'))if(!wanted.has(old.dataset.key))old.remove();svg.prepend(fragment);
}
function local(e){const matrix=svg.getScreenCTM();if(!matrix)return [0,0];const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());return [p.x,p.y];}
function manual(){pauseManual()}
function assign(k,value){if(!P[k])return;set(k,Math.max(P[k][0],Math.min(P[k][1],value)));}
function notify(keys){for(const k of keys)inputs[k]?.dispatchEvent(new Event('input',{bubbles:true}));draw();}
svg.addEventListener('pointerdown',e=>{const circle=e.target.closest('circle');if(!circle||!R)return;e.preventDefault();e.stopPropagation();manual();selected=circle.dataset.key;const n=nodes.find(n=>n.key===selected);const start=local(e);drag={kind:'node',node:{...n},start,vals:{...v},pointer:e.pointerId,angle:Math.atan2(start[1]-n.pivot[1],start[0]-n.pivot[0])};stage.setPointerCapture(e.pointerId);readout.textContent=n.label+' — drag to adjust; double-click to reset';update();});
stage.addEventListener('pointerdown',e=>{if(e.target.closest('#pose-toolbar')||!panMode)return;e.preventDefault();drag={kind:'pan',start:[e.clientX,e.clientY],x:panX,y:panY,pointer:e.pointerId};stage.setPointerCapture(e.pointerId);});
stage.addEventListener('pointermove',e=>{if(!drag||drag.pointer!==e.pointerId)return;e.preventDefault();if(drag.kind==='pan'){panX=drag.x+e.clientX-drag.start[0];panY=drag.y+e.clientY-drag.start[1];transform();return;}const p=local(e),n=drag.node,dx=p[0]-drag.start[0],dy=p[1]-drag.start[1];let changed=[n.key];
 if(n.kind==='twist'){assign(n.key,drag.vals[n.key]+dx/100);}
 else if(n.kind==='root'){assign('RootX',drag.vals.RootX+dx);assign('RootY',drag.vals.RootY+dy);changed=['RootX','RootY'];}
 else if(n.kind==='head'){if(headFacing()){assign('HeadNod',drag.vals.HeadNod+dx/60*headFacing());changed=['HeadNod'];}else{assign('HeadTilt',drag.vals.HeadTilt+dx/60);assign('HeadNod',drag.vals.HeadNod+dy/60);changed=['HeadTilt','HeadNod'];}}
 else if(n.kind==='curl'){assign(n.key,drag.vals[n.key]-dy/80);}
 else{let delta=Math.atan2(p[1]-n.pivot[1],p[0]-n.pivot[0])-drag.angle;delta=Math.atan2(Math.sin(delta),Math.cos(delta));assign(n.key,fromAngle(n.angle+delta*180/Math.PI,...n.coeff));}
 notify(changed);readout.textContent=changed.map(k=>k+' '+(n.kind==='twist'?((/^WristTwist/.test(k)?(twistState(k.slice(-1),false)?.selectedDeg||0):v[k]*(window.RigTwist?.maxDegrees(k)||60))).toFixed(0)+'° '+(/^WristTwist/.test(k)?'(authored hand)':'(skin projection)'):v[k].toFixed(2))).join(' · ');
});
function finish(e){if(drag?.pointer===e.pointerId){drag=null;if(stage.hasPointerCapture(e.pointerId))stage.releasePointerCapture(e.pointerId);}}stage.addEventListener('pointerup',finish);stage.addEventListener('pointercancel',finish);
svg.addEventListener('dblclick',e=>{const k=e.target.closest('circle')?.dataset.key;if(k){manual();assign(k,P[k][2]);notify([k]);}});
svg.addEventListener('keydown',e=>{const k=e.target.closest('circle')?.dataset.key;if(!k||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key))return;e.preventDefault();manual();let keys=[k];if(k==='RootX'){if(e.key==='Home'){assign('RootX',P.RootX[2]);assign('RootY',P.RootY[2]);keys=['RootX','RootY']}else{const key=['ArrowUp','ArrowDown'].includes(e.key)?'RootY':'RootX',step=(P[key][1]-P[key][0])/100;assign(key,v[key]+(['ArrowLeft','ArrowUp'].includes(e.key)?-step:step));keys=[key]}}else{const step=(P[k][1]-P[k][0])/100;assign(k,e.key==='Home'?P[k][2]:v[k]+(['ArrowLeft','ArrowDown'].includes(e.key)?-step:step))}notify(keys)});
toolbar.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a==='playback'){const p=window.SVPlayback;if(p){if(p.state.playing)p.pause();else p.play();signal()}}else if(a==='handL'||a==='handR'){const side=a.slice(-1),hand=collect().filter(n=>n.key.startsWith('Hand'+side)||n.key==='Wrist'+side);if(hand.length){handFocusSide=side;const pts=hand.flatMap(n=>[n.pivot,n.end]),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);Z.handFocus=[Math.floor(Math.min(...xs)-65),Math.floor(Math.min(...ys)-65),Math.ceil(Math.max(...xs)-Math.min(...xs)+130),Math.ceil(Math.max(...ys)-Math.min(...ys)+130)];const menu=document.getElementById('zoom');if(!menu.querySelector('option[value=handFocus]'))menu.add(new Option('Focused hand','handFocus'));menu.value='handFocus';twistMode=false;nodesOn=true;panX=panY=0;setZoom(1);draw();readout.textContent=side+' hand: drag each finger joint up / down to curl; sliders provide linked curl and spread.'}else readout.textContent='This hand is not delivered in the current view.';}else if(a==='controls'||a==='layers')togglePanel(a);else if(a==='nodes'){nodesOn=!nodesOn;pref.nodes=nodesOn;save();update();}else if(a==='twist'){twistMode=!twistMode;selected='';readout.textContent=twistMode?'Purple handles: drag left / right to twist. Hands snap to authored angles without fades; missing angles are clamped.':'Blue handles: drag to bend and pose.';update();}else if(a==='pan'){panMode=!panMode;}else if(a==='in'||a==='out')setZoom(zoom+(a==='in'?.2:-.2));else if(a==='fit'){panX=panY=0;if(document.getElementById('zoom').value==='handFocus'){document.getElementById('zoom').value='full';draw()}setZoom(1);}toolbar.querySelector('[data-action=nodes]').setAttribute('aria-pressed',String(nodesOn));toolbar.querySelector('[data-action=twist]').setAttribute('aria-pressed',String(twistMode));toolbar.querySelector('[data-action=pan]').setAttribute('aria-pressed',String(panMode));signal();});
toolbar.querySelector('#pose-zoom').addEventListener('input',e=>setZoom(+e.target.value));
stage.addEventListener('wheel',e=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();setZoom(zoom*Math.exp(-e.deltaY*.001));},{passive:false});
for(const heading of document.querySelectorAll('#ui h3')){heading.classList.add('pose-fold');heading.setAttribute('tabindex','0');heading.setAttribute('role','button');heading.setAttribute('aria-expanded','true');const fold=()=>{const open=heading.getAttribute('aria-expanded')!=='false';heading.setAttribute('aria-expanded',String(!open));let row=heading.nextElementSibling;while(row&&row.tagName!=='H3'){row.hidden=open;row.dataset.poseFoldHidden=open?'true':'';row=row.nextElementSibling;}};heading.addEventListener('click',fold);heading.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fold();}});}
window.PoseEditor={update,togglePanel,setZoom,
exportState(){return{values:{...v},autoHandAngles:document.getElementById('autohands').checked,handViews:Object.fromEntries(['L','R'].map(side=>[side,twistState(side,false)?.L[0]?.e.src||document.getElementById('view').value])),manual:!document.getElementById('auto').checked,zoom,panX,panY,nodesOn,twistMode}},
importState(snapshot,{pose=true}={}){if(!snapshot)return;if(snapshot.autoHandAngles!=null)document.getElementById('autohands').checked=!!snapshot.autoHandAngles;if(pose&&snapshot.manual){manual();for(const [k,x]of Object.entries(snapshot.values||{}))if(P[k]&&!inputs[k]?.disabled&&Number.isFinite(x))assign(k,x);for(const side of ['L','R']){const src=snapshot.handViews?.[side];if(src){const angle=R.handAngles?.[side]?.E.find(e=>e.src===src);set('WristTwist'+side,(angle?.deg||0)/WT_FULL)}}draw()}panX=Number.isFinite(snapshot.panX)?snapshot.panX:0;panY=Number.isFinite(snapshot.panY)?snapshot.panY:0;nodesOn=snapshot.nodesOn!==false;twistMode=!!snapshot.twistMode;setZoom(snapshot.zoom||1);signal()},
showAll(){pref.hideControls=false;pref.hideLayers=false;pref.nodes=true;nodesOn=true;for(const panel of ['controls','layers']){document.body.classList.remove('pose-hide-'+panel);toolbar.querySelector('[data-action='+panel+']').setAttribute('aria-pressed','true')}for(const heading of document.querySelectorAll('#ui h3.pose-fold'))heading.setAttribute('aria-expanded','true');for(const row of document.querySelectorAll('#ui [data-pose-fold-hidden=true]'))row.hidden=false;document.querySelector('#lpbody').style.display='';save();update()},
setTwistMode(value){twistMode=!!value;selected='';toolbar.querySelector('[data-action=twist]').setAttribute('aria-pressed',String(twistMode));readout.textContent=twistMode?'Purple handles: drag left / right to twist. Hands snap to authored angles without fades; missing angles are clamped.':'Blue handles: drag to bend and pose.';update();},get state(){return {zoom,panX,panY,nodesOn,twistMode,hideControls:!!pref.hideControls,hideLayers:!!pref.hideLayers,selected,nodes:nodes.map(({key,end,pivot,kind})=>({key,end,pivot,kind}))}}};new ResizeObserver(update).observe(stage);toolbar.querySelector('[data-action=nodes]').setAttribute('aria-pressed',String(nodesOn));update();signal();
})();
