(() => {
const style=document.createElement('style');style.textContent=`
#workspace-tools{display:flex;flex-wrap:wrap;gap:5px;align-items:center;position:sticky;top:0;z-index:30;padding:8px 14px;background:#172434;border-bottom:1px solid var(--line);font-size:14px}#workspace-tools button{background:#252b35;color:#e3e6ec;border:1px solid #425063;border-radius:5px;padding:7px 10px;min-height:34px;font-size:14px;cursor:pointer}#workspace-tools button[aria-pressed=true]{border-color:#72c8ff;background:#1e3a50}
body.workspace-hide-gallery #r-preview .cols{grid-template-columns:minmax(0,1fr)!important}body.workspace-hide-gallery #r-preview .cols>.scroll{display:none}body.workspace-hide-sidebar #botside{display:none}body.workspace-hide-sidebar #r-bot .cols{grid-template-columns:minmax(0,1fr)!important}body.workspace-hide-sliders .rc{grid-template-columns:minmax(0,1fr)!important}body.workspace-hide-sliders .rc .rp{display:none}body.workspace-hide-preview-controls #pvtop,body.workspace-hide-preview-controls #pvclips{display:none}body.workspace-hide-notes .note{display:none}
body.workspace-focus>header,body.workspace-focus #pvtop,body.workspace-focus #pvclips,body.workspace-focus #r-preview .cols>.scroll,body.workspace-focus #pvnote{display:none}body.workspace-focus #r-preview .cols{grid-template-columns:minmax(0,1fr)!important}body.workspace-focus main{height:calc(100vh - 44px)}body.workspace-focus #workspace-tools{height:auto;min-height:44px}
.card.folded>:not(h2){display:none}.card h2{cursor:pointer}.card h2:after{content:' ▾';margin-left:auto;color:#8bd7ff}.card.folded h2:after{content:' ▸'}@media(max-width:760px){#workspace-tools{padding:5px 8px}body.workspace-focus main{height:auto}body.workspace-focus #rigwrap{height:80vh;min-height:650px}}
`;document.head.append(style);
let pref={};try{pref=JSON.parse(localStorage.getItem('shadowveil.master.workspace.v1')||'{}')}catch{}
const tools=document.getElementById('workspace-tools')||document.createElement('div');tools.replaceChildren();const caption=document.createElement('strong');caption.textContent='Show / hide panels';tools.append(caption);tools.id='workspace-tools';tools.setAttribute('aria-label','Workspace panels');document.querySelector('header').after(tools);
function activeEditor(){try{return document.querySelector('.route.on iframe')?.contentWindow.PoseEditor}catch{return null}}
function syncRigButtons(){const state=activeEditor()?.state;for(const b of tools.querySelectorAll('[data-rig-panel]'))if(state)b.textContent=(state[b.dataset.rigPanel==='controls'?'hideControls':'hideLayers']?'Show ':'Hide ')+(b.dataset.rigPanel==='controls'?'rig controls':'layers');const b=tools.querySelector('[data-rig-twist]');if(b&&state)b.textContent=state.twistMode?'Bend handles':'Twist handles'}window.addEventListener('shadowveil-workspace-change',syncRigButtons);
const playback=document.createElement('button');playback.type='button';playback.dataset.playback='true';playback.textContent='Play motion';tools.insertBefore(playback,caption);function activePlayback(){try{return document.querySelector('.route.on iframe')?.contentWindow.SVPlayback}catch{return null}}function syncPlayback(){const p=activePlayback();playback.textContent=p?.state.playing?'Pause motion':'Play motion';playback.setAttribute('aria-pressed',String(!!p?.state.playing))}playback.onclick=()=>{const p=activePlayback();if(p?.state.ready){if(p.state.playing)p.pause();else p.play();syncPlayback()}else{playback.textContent='Rig loading…'}};setInterval(syncPlayback,500);
const buttons=[['gallery','Videos'],['preview-controls','Preview controls'],['sidebar','Reports'],['sliders','Sliders'],['notes','Notes'],['focus','Focus pose']];
function apply(){for(const [key,label]of buttons){const on=!!pref[key];const button=tools.querySelector('[data-panel="'+key+'"]');if(button)button.textContent=key==='focus'?(on?'Exit focus':'Focus pose'):(on?'Show ':'Hide ')+label.toLowerCase();document.body.classList.toggle(key==='focus'?'workspace-focus':'workspace-hide-'+key,on);tools.querySelector('[data-panel="'+key+'"]')?.setAttribute('aria-pressed',String(key==='focus'?on:!on));}requestAnimationFrame(()=>window.dispatchEvent(new Event('resize')));}
for(const [key,label]of buttons){const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.panel=key;b.addEventListener('click',()=>{pref[key]=!pref[key];try{localStorage.setItem('shadowveil.master.workspace.v1',JSON.stringify(pref))}catch{}apply();});tools.append(b);}const restore=document.createElement('button');restore.type='button';restore.textContent='Show all';restore.onclick=()=>{pref={};activeEditor()?.showAll();try{localStorage.setItem('shadowveil.pose.workspace.v1',JSON.stringify({hideControls:false,hideLayers:false,nodes:true}))}catch{}for(const card of document.querySelectorAll('.card.folded')){card.classList.remove('folded');card.querySelector('h2')?.setAttribute('aria-expanded','true')}syncRigButtons();try{localStorage.removeItem('shadowveil.master.workspace.v1')}catch{}apply();};tools.append(restore);for(const [panel,label]of [['controls','Hide rig controls'],['layers','Hide layers']]){const button=document.createElement('button');button.type='button';button.textContent=label;button.dataset.rigPanel=panel;button.onclick=()=>{try{const editor=activeEditor();if(editor){editor.togglePanel(panel);syncRigButtons();}else{button.textContent='Rig loading…';setTimeout(()=>button.textContent=label,1500)}}catch{button.textContent='Open Live rig first';setTimeout(()=>button.textContent=label,1500)}};tools.append(button);}const twists=document.createElement('button');twists.type='button';twists.textContent='Twist handles';twists.dataset.rigTwist='true';twists.onclick=()=>{try{const editor=activeEditor();if(editor){const mode=!editor.state.twistMode;editor.setTwistMode(mode);twists.textContent=mode?'Bend handles':'Twist handles';}else{twists.textContent='Open Live rig first';setTimeout(()=>twists.textContent='Twist handles',1500)}}catch{}};tools.append(twists);apply();
new MutationObserver(()=>{for(const h of document.querySelectorAll('.card h2:not([data-fold-ready])')){h.dataset.foldReady='true';h.tabIndex=0;h.setAttribute('role','button');h.setAttribute('aria-expanded','true');const toggle=()=>{const collapsed=h.parentElement.classList.toggle('folded');h.setAttribute('aria-expanded',String(!collapsed));};h.addEventListener('click',e=>{if(!e.target.closest('a'))toggle();});h.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle();}});}}).observe(document.querySelector('main'),{childList:true,subtree:true});
})();
