#!/usr/bin/env python3
"""Regenerate patched copies of the grok_build clean-room pages for the :8765 server.
The originals (reference/grok_build/public/...) expect public/ as web root and use
root-absolute /clean-room/... URLs (or bare apose.png/tpose.png), which 404 when
/workspace/shadowveil is the web root. These copies point at the same files in the
reference clone via relative URLs. The reference clone itself is not modified."""
import pathlib, re, json
HERE = pathlib.Path(__file__).resolve().parent
PUB = HERE.parent.parent / 'reference/grok_build/public'
REL = '../../reference/grok_build/public/clean-room/'
BANNER = '<!-- GENERATED by app/cleanroom/build.py from reference/grok_build/public/{src}; do not edit, rerun build.py -->\n'

# 1) current clean room (clean-room/index.html)
s = (PUB / 'clean-room/index.html').read_text()
n = s.count('"/clean-room/')
s = s.replace('"/clean-room/', '"' + REL)
# rig/apose.json lists part srcs as root-absolute /clean-room/... ; rewrite them at load time
old = 'img.src = part.src;'
assert s.count(old) == 1, 'apose.json loader changed upstream'
s = s.replace(old, 'img.src = part.src.replace(/^\\/clean-room\\//, "%s");' % REL)
assert '"/clean-room/' not in s
(HERE / 'index.html').write_text(BANNER.format(src='clean-room/index.html') + s)

# 2) older static clean room (clean-room.html): bare apose.png / tpose.png, which only exist under clean-room/
t = (PUB / 'clean-room.html').read_text()
for name in ('apose.png', 'tpose.png'):
    assert t.count('src: "%s"' % name) == 1
    assert (PUB / 'clean-room' / name).is_file()
    t = t.replace('src: "%s"' % name, 'src: "%s%s"' % (REL, name))
(HERE / 'static.html').write_text(BANNER.format(src='clean-room.html') + t)
print('patched', n, 'root-absolute /clean-room/ refs in index.html; wrote index.html, static.html')

# 3) held-frame lane (layers/anim/<clip>.png) has no onerror upstream; talk-speak/ask/laugh have no held frame,
#    so hide the broken img and label the lane instead of showing a broken-image icon (no art is invented).
#    (held-frame onerror, added by the pose-driver worker)
s = (HERE / 'index.html').read_text()
old = 'img.alt = current.name;\n      thumbs.append(img);'
assert s.count(old) == 1, 'held-frame lane changed upstream'
s = s.replace(old, 'img.alt = current.name;\n      img.onerror = () => { thumbs.remove(); track.classList.add("empty"); track.textContent = "No held frame for this clip"; };\n      thumbs.append(img);')
(HERE / 'index.html').write_text(s)
print('patched held-frame onerror')

# 4) don't even request cuts that don't exist (keeps the page at 0 failed requests): only clips with a
#    layers/hierarchy/anim/<id>/ folder get part lanes, only clips with layers/anim/<id>.png get a held frame.
s = (HERE / 'index.html').read_text()
CR = PUB / 'clean-room/layers'
has_part = sorted(d.name for d in (CR / 'hierarchy/anim').iterdir() if (d / 'hair.png').is_file() and (d / 'body.png').is_file())
has_held = sorted(f.stem for f in (CR / 'anim').glob('*.png'))
a = 'img.src = "%slayers/hierarchy/anim/" + current.id + "/" + group.file;' % REL
b = 'img.src = "%slayers/anim/" + current.id + ".png?v=1";' % REL
assert s.count(a) == 1 and s.count(b) == 1, 'layer lanes changed upstream'
s = s.replace(a, 'if (HAS_PART.includes(current.id)) ' + a[:-1] + '; else queueMicrotask(() => img.onerror());')
s = s.replace(b, 'if (HAS_HELD.includes(current.id)) ' + b[:-1] + '; else queueMicrotask(() => img.onerror());')
s = s.replace('let heldFrame = null;', 'let heldFrame = null;\nconst HAS_PART = %s;\nconst HAS_HELD = %s;' % (json.dumps(has_part), json.dumps(has_held)), 1)
(HERE / 'index.html').write_text(s)
print('lanes gated: %d part cuts, %d held frames' % (len(has_part), len(has_held)))
